export const routesApp = {
  home: "/",
  campaigns: "/campaigns",
  clubs: "/cashtags",
  badgesOverview: "/badges/overview",
  advertisers: "/advertisers",
  dashboard: "/dashboard",
  createBounty: "/bounties/create",
  help: "/help",
  leaderboard: "/creators/leaderboard",
  referrals: "/referrals",
  points: "/points",
  createBadge: "/badges/create",
  plugins: "/plugins",
  hooks: "/hooks",
};
